baseURL = "https://username.github.io/"
title = "Hugo-Flex Demo Site"
author = "Jane Doe"
languageCode = "en-us"
pygmentsCodeFences = true
enableRobotsTXT = true
theme = "hugo-flex"
publishDir = "docs"

[permalinks]
posts = "/:filename/"
pages = "/:filename/"

[params]
width = "42rem"
description = "Jane Doe's webpages"
color = "black"
rss = "To subscribe to this RSS feed, copy the address in the address bar and paste it into your favorite feed reader."
AuthorName = "Jane Doe"
schema = true
opengraph = true
twittercards = true
summaries = false

[menu]

  [[menu.nav]]
  name = "About"
  url = "about/"
  weight = 1.0

  [[menu.nav]]
  name = "Blog"
  url = "posts/"
  weight = 2.0

  [[menu.nav]]
  name = "Tags"
  url = "tags/"
  weight = 3.0

  [[menu.nav]]
  name = "Categories"
  url = "categories/"
  weight = 4.0
